# Generated by Django 5.2.12 on 2026-03-10 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='time',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voters.voter'),
        ),
    ]
