# Generated by Django 5.2.12 on 2026-03-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='face_image',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='iris_image',
        ),
        migrations.AddField(
            model_name='voter',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='gender',
            field=models.CharField(default=18, max_length=10),
            preserve_default=False,
        ),
    ]
